---
{{- if and .Values.tls.certData .Values.tls.keyData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.certificateSecret }}
  namespace: tfe
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certData }}
  tls.key: {{ .Values.tls.keyData }}
{{- end }}

{{- if .Values.tls.caCertData }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-ca-certificates
  namespace: tfe
data:
  {{ .Values.tls.caCertFileName }}: {{ .Values.tls.caCertData }}
{{- end }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-env-secrets
  namespace: tfe
data:
{{- include "helpers.list-env-secrets" . | indent 2 }}
{{- if .Values.env.secretsFilePath }}
{{- include "helpers.enc-b64-secrets-file" . | indent 2 }}
{{- end }}