{{- if .Values.serviceAccount.enabled }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.name}}
  name: {{ .Values.serviceAccount.name }}
  {{- else }}
  name: {{ .Release.Namespace }}
  {{- end }}
  namespace: tfe
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
